project_name: ecs-dereg-ctl

builds:
  - env:
    - GO111MODULE=on
    - CGO_ENABLED=0
  - binary: ecs-dereg-ctl
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
release:
  github:
    owner: wreulicke
    name: ecs-dereg-ctl